- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Create application directory
  ansible.builtin.import_role:
    name: common
    tasks_from: app_content_cleanup

- name: Donwload Frontend Content
  ansible.builtin.import_role:
    name: common
    tasks_from: download_app_content

- name: Copy Nginx configuration
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Copy RoboShop configuration file
  ansible.builtin.template:
    src: robo-shop.conf
    dest: /etc/nginx/conf.d/robo-shop.conf
