- name: Configure YUM Repos
  ansible.builtin.shell: curl {{item}} | bash
  loop:
    - https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh
    - https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh

- name: Install RabbitMQ
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: Start RabbitMQ Service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Add Rabbit MQ user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: "{{ lookup('amazon.aws.aws_ssm', '{{env}}.roboshop.rabbitmq.MQ_PASS', region='us-east-1' ) }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present