- name: Install goLang
  ansible.builtin.dnf:
    name: golang
    state: installed

- name: Load App pre requisite
  ansible.builtin.import_tasks:
    file: app-prerqe.yaml

- name: python dependencies
  ansible.builtin.shell: go mod init {{component}} ; go get ; go build
  args:
    chdir: /app

- name: SystemD setup
  ansible.builtin.import_tasks:
    file: systemd.yaml

- name: Load schema files
  ansible.builtin.import_tasks:
    file: schema.yaml
  when: is_schema_needed