- name: Install maven
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: Load App  pre requisite
  ansible.builtin.import_tasks:
    file: app-prerqe.yaml

- name: Npm install dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
args:
  chdir: /app
  
  - name: SystemD setup
    ansible.builtin.import_tasks:
      file: systemd.yaml
  
  - name: Load schema files
    ansible.builtin.import_tasks:
      file: schema.yaml
    when: is_schema_needed